declare class Sprite_Character extends Sprite {
    protected _character: Game_Character | null;
    protected _balloonDuration: number;
    protected _tilesetId: number;
    protected _upperBody: Sprite | null;
    protected _lowerBody: Sprite | null;
    protected _tileId: number;
    protected _characterName: string;
    protected _characterIndex: number;
    protected _isBigCharacter: boolean;
    protected _bushDepth: number;
    constructor(character: Game_Character);
    initialize(character: Game_Character): void;
    initMembers(): void;
    setCharacter(character: Game_Character): void;
    checkCharacter(character: Game_Character): boolean;
    update(): void;
    updateVisibility(): void;
    isTile(): boolean;
    isObjectCharacter(): boolean;
    isEmptyCharacter(): boolean;
    tilesetBitmap(tileId: number): Bitmap;
    updateBitmap(): void;
    isImageChanged(): boolean;
    setTileBitmap(): void;
    setCharacterBitmap(): void;
    updateFrame(): void;
    updateTileFrame(): void;
    updateCharacterFrame(): void;
    characterBlockX(): number;
    characterBlockY(): number;
    characterPatternX(): number;
    characterPatternY(): number;
    patternWidth(): number;
    patternHeight(): number;
    updateHalfBodySprites(): void;
    createHalfBodySprites(): void;
    updatePosition(): void;
    updateOther(): void;
}
