declare class Sprite_Gauge extends Sprite {
    protected _battler: Game_Battler | null;
    protected _statusType: string;
    protected _value: number;
    protected _maxValue: number;
    protected _targetValue: number;
    protected _targetMaxValue: number;
    protected _duration: number;
    protected _flashingCount: number;
    initialize(): void;
    initMembers(): void;
    destroy(options?: {
        children?: boolean;
        texture?: boolean;
        baseTexture?: boolean;
    }): void;
    createBitmap(): void;
    bitmapWidth(): number;
    bitmapHeight(): number;
    textHeight(): number;
    gaugeHeight(): number;
    gaugeX(): number;
    labelY(): number;
    labelFontFace(): string;
    labelFontSize(): number;
    valueFontFace(): string;
    valueFontSize(): number;
    setup(battler: Game_Battler, statusType: string): void;
    update(): void;
    updateBitmap(): void;
    updateTargetValue(value: number, maxValue: number): void;
    smoothness(): 5 | 20;
    updateGaugeAnimation(): void;
    updateFlashing(): void;
    flashingColor1(): number[];
    flashingColor2(): number[];
    isValid(): boolean;
    currentValue(): number;
    currentMaxValue(): number;
    label(): string;
    gaugeBackColor(): string;
    gaugeColor1(): string;
    gaugeColor2(): string;
    labelColor(): string;
    labelOutlineColor(): string;
    labelOutlineWidth(): number;
    valueColor(): string;
    valueOutlineColor(): string;
    valueOutlineWidth(): number;
    redraw(): void;
    drawGauge(): void;
    drawGaugeRect(x: number, y: number, width: number, height: number): void;
    gaugeRate(): number;
    drawLabel(): void;
    setupLabelFont(): void;
    measureLabelWidth(): number;
    labelOpacity(): 255 | 160;
    drawValue(): void;
    setupValueFont(): void;
}
