declare class Game_Screen {
    protected _brightness: number;
    protected _tone: any;
    protected _flashColor: any;
    protected _shake: number;
    protected _zoomX: number;
    protected _zoomY: number;
    protected _zoomScale: any;
    protected _weatherType: any;
    protected _weatherPower: any;
    protected _pictures: any;
    protected _fadeOutDuration: number;
    protected _fadeInDuration: number;
    protected _toneTarget: number[];
    protected _toneDuration: number;
    protected _flashDuration: number;
    protected _shakePower: number;
    protected _shakeSpeed: number;
    protected _shakeDuration: number;
    protected _shakeDirection: number;
    protected _zoomScaleTarget: number;
    protected _zoomDuration: number;
    protected _weatherPowerTarget: number;
    protected _weatherDuration: number;
    constructor();
    initialize(...args: any[]): void;
    clear(): void;
    onBattleStart(): void;
    brightness(): number;
    tone(): any;
    flashColor(): any;
    shake(): number;
    zoomX(): number;
    zoomY(): number;
    zoomScale(): any;
    weatherType(): any;
    weatherPower(): any;
    picture(pictureId: number): any;
    realPictureId(pictureId: number): number;
    clearFade(): void;
    clearTone(): void;
    clearFlash(): void;
    clearShake(): void;
    clearZoom(): void;
    clearWeather(): void;
    clearPictures(): void;
    eraseBattlePictures(): void;
    maxPictures(): number;
    startFadeOut(duration: number): void;
    startFadeIn(duration: number): void;
    startTint(tone: any, duration: number): void;
    startFlash(color: any, duration: number): void;
    startShake(power: number, speed: number, duration: number): void;
    startZoom(x: number, y: number, scale: number, duration: number): void;
    setZoom(x: number, y: number, scale: number): void;
    changeWeather(type: string, power: number, duration: number): void;
    update(): void;
    updateFadeOut(): void;
    updateFadeIn(): void;
    updateTone(): void;
    updateFlash(): void;
    updateShake(): void;
    updateZoom(): void;
    updateWeather(): void;
    updatePictures(): void;
    startFlashForDamage(): void;
    showPicture(pictureId: number, name: string, origin: Point, x: number, y: number, scaleX: number, scaleY: number, opacity: number, blendMode: number): void;
    movePicture(pictureId: number, origin: Point, x: number, y: number, scaleX: number, scaleY: number, opacity: number, blendMode: number, duration: number, easingType: any): void;
    rotatePicture(pictureId: number, speed: number): void;
    tintPicture(pictureId: number, tone: any, duration: any): void;
    erasePicture(pictureId: number): void;
}
