declare class Window_ShopNumber extends Window_Selectable {
    protected _item: ItemObject | null;
    protected _max: number;
    protected _price: number;
    protected _number: number;
    protected _currencyUnit: any;
    protected _buttons: Sprite_Button[];
    initialize(rect: Rectangle): void;
    isScrollEnabled(): boolean;
    number(): number;
    setup(item: ItemObject | null, max: number, price: number): void;
    setCurrencyUnit(currencyUnit: any): void;
    createButtons(): void;
    placeButtons(): void;
    totalButtonWidth(): number;
    buttonSpacing(): number;
    refresh(): void;
    drawCurrentItemName(): void;
    drawMultiplicationSign(): void;
    multiplicationSign(): string;
    multiplicationSignX(): number;
    drawNumber(): void;
    drawHorzLine(): void;
    drawTotalPrice(): void;
    itemNameY(): number;
    totalPriceY(): number;
    buttonY(): number;
    cursorWidth(): number;
    cursorX(): number;
    maxDigits(): number;
    update(): void;
    playOkSound(): void;
    processNumberChange(): void;
    changeNumber(amount: number): void;
    itemRect(): Rectangle;
    isTouchOkEnabled(): boolean;
    onButtonUp(): void;
    onButtonUp2(): void;
    onButtonDown(): void;
    onButtonDown2(): void;
    onButtonOk(): void;
}
