declare class Scene_Map extends Scene_Message {
    protected _waitCount: number;
    protected _encounterEffectDuration: number;
    protected _mapLoaded: boolean;
    protected _touchCount: number;
    protected _menuEnabled: boolean;
    protected _transfer: boolean;
    protected _lastMapWasNull: boolean;
    protected menuCalling: boolean;
    protected _mapNameWindow: Window_MapName;
    protected _spriteset: Spriteset_Map;
    protected _menuButton: Sprite_Button;
    initialize(): void;
    create(): void;
    isReady(): boolean;
    onMapLoaded(): void;
    onTransfer(): void;
    start(): void;
    onTransferEnd(): void;
    shouldAutosave(): boolean;
    update(): void;
    updateMainMultiply(): void;
    updateMain(): void;
    isPlayerActive(): boolean;
    isFastForward(): boolean;
    stop(): void;
    isBusy(): boolean;
    terminate(): void;
    needsFadeIn(): boolean;
    needsSlowFadeOut(): boolean | null;
    updateWaitCount(): boolean;
    updateDestination(): void;
    updateMenuButton(): void;
    hideMenuButton(): void;
    updateMapNameWindow(): void;
    isMenuEnabled(): boolean;
    isMapTouchOk(): boolean;
    processMapTouch(): void;
    isAnyButtonPressed(): boolean;
    onMapTouch(): void;
    isSceneChangeOk(): boolean;
    updateScene(): void;
    createDisplayObjects(): void;
    createSpriteset(): void;
    createAllWindows(): void;
    createMapNameWindow(): void;
    mapNameWindowRect(): Rectangle;
    createButtons(): void;
    createMenuButton(): void;
    updateTransferPlayer(): void;
    updateEncounter(): void;
    updateCallMenu(): void;
    isMenuCalled(): boolean;
    callMenu(): void;
    updateCallDebug(): void;
    isDebugCalled(): boolean;
    fadeInForTransfer(): void;
    fadeOutForTransfer(): void;
    launchBattle(): void;
    stopAudioOnBattleStart(): void;
    startEncounterEffect(): void;
    updateEncounterEffect(): void;
    snapForBattleBackground(): void;
    startFlashForEncounter(duration: number): void;
    encounterEffectSpeed(): number;
}
